/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const camelCase: typeof import('lodash-es')['camelCase']
  const camelize: typeof import('vue')['camelize']
  const computed: typeof import('vue')['computed']
  const createAdProps: typeof import('./src/composables/ad')['createAdProps']
  const createOne: typeof import('@vuetify/one')['createOne']
  const defineStore: typeof import('pinia')['defineStore']
  const h: typeof import('vue')['h']
  const kebabCase: typeof import('lodash-es')['kebabCase']
  const mergeProps: typeof import('vue')['mergeProps']
  const nextTick: typeof import('vue')['nextTick']
  const onBeforeMount: typeof import('vue')['onBeforeMount']
  const onBeforeRouteLeave: typeof import('vue-router')['onBeforeRouteLeave']
  const onBeforeRouteUpdate: typeof import('vue-router')['onBeforeRouteUpdate']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const onMounted: typeof import('vue')['onMounted']
  const onScopeDispose: typeof import('vue')['onScopeDispose']
  const onServerPrefetch: typeof import('vue')['onServerPrefetch']
  const ref: typeof import('vue')['ref']
  const shallowRef: typeof import('vue')['shallowRef']
  const storeToRefs: typeof import('pinia')['storeToRefs']
  const upperFirst: typeof import('lodash-es')['upperFirst']
  const useAd: typeof import('./src/composables/ad')['useAd']
  const useAttrs: typeof import('vue')['useAttrs']
  const useAuthStore: typeof import('@vuetify/one')['useAuthStore']
  const useCosmic: typeof import('./src/composables/cosmic')['useCosmic']
  const useDate: typeof import('vuetify')['useDate']
  const useDisplay: typeof import('vuetify')['useDisplay']
  const useGoTo: typeof import('vuetify')['useGoTo']
  const useGtag: typeof import('vue-gtag-next')['useGtag']
  const useHttpStore: typeof import('@vuetify/one')['useHttpStore']
  const useI18n: typeof import('vue-i18n')['useI18n']
  const useOneStore: typeof import('@vuetify/one')['useOneStore']
  const usePlayground: typeof import('./src/composables/playground')['usePlayground']
  const useRoute: typeof import('vue-router')['useRoute']
  const useRouter: typeof import('vue-router')['useRouter']
  const useRtl: typeof import('vuetify')['useRtl']
  const useTheme: typeof import('vuetify')['useTheme']
  const useUserStore: typeof import('@vuetify/one')['useUserStore']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface ComponentCustomProperties {
    readonly camelCase: UnwrapRef<typeof import('lodash-es')['camelCase']>
    readonly camelize: UnwrapRef<typeof import('vue')['camelize']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createAdProps: UnwrapRef<typeof import('./src/composables/ad')['createAdProps']>
    readonly createOne: UnwrapRef<typeof import('@vuetify/one')['createOne']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly kebabCase: UnwrapRef<typeof import('lodash-es')['kebabCase']>
    readonly mergeProps: UnwrapRef<typeof import('vue')['mergeProps']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly upperFirst: UnwrapRef<typeof import('lodash-es')['upperFirst']>
    readonly useAd: UnwrapRef<typeof import('./src/composables/ad')['useAd']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useAuthStore: UnwrapRef<typeof import('@vuetify/one')['useAuthStore']>
    readonly useCosmic: UnwrapRef<typeof import('./src/composables/cosmic')['useCosmic']>
    readonly useDate: UnwrapRef<typeof import('vuetify')['useDate']>
    readonly useDisplay: UnwrapRef<typeof import('vuetify')['useDisplay']>
    readonly useGoTo: UnwrapRef<typeof import('vuetify')['useGoTo']>
    readonly useGtag: UnwrapRef<typeof import('vue-gtag-next')['useGtag']>
    readonly useHttpStore: UnwrapRef<typeof import('@vuetify/one')['useHttpStore']>
    readonly useI18n: UnwrapRef<typeof import('vue-i18n')['useI18n']>
    readonly useOneStore: UnwrapRef<typeof import('@vuetify/one')['useOneStore']>
    readonly usePlayground: UnwrapRef<typeof import('./src/composables/playground')['usePlayground']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useRtl: UnwrapRef<typeof import('vuetify')['useRtl']>
    readonly useTheme: UnwrapRef<typeof import('vuetify')['useTheme']>
    readonly useUserStore: UnwrapRef<typeof import('@vuetify/one')['useUserStore']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
  }
}
declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    readonly camelCase: UnwrapRef<typeof import('lodash-es')['camelCase']>
    readonly camelize: UnwrapRef<typeof import('vue')['camelize']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createAdProps: UnwrapRef<typeof import('./src/composables/ad')['createAdProps']>
    readonly createOne: UnwrapRef<typeof import('@vuetify/one')['createOne']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly kebabCase: UnwrapRef<typeof import('lodash-es')['kebabCase']>
    readonly mergeProps: UnwrapRef<typeof import('vue')['mergeProps']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly upperFirst: UnwrapRef<typeof import('lodash-es')['upperFirst']>
    readonly useAd: UnwrapRef<typeof import('./src/composables/ad')['useAd']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useAuthStore: UnwrapRef<typeof import('@vuetify/one')['useAuthStore']>
    readonly useCosmic: UnwrapRef<typeof import('./src/composables/cosmic')['useCosmic']>
    readonly useDate: UnwrapRef<typeof import('vuetify')['useDate']>
    readonly useDisplay: UnwrapRef<typeof import('vuetify')['useDisplay']>
    readonly useGoTo: UnwrapRef<typeof import('vuetify')['useGoTo']>
    readonly useGtag: UnwrapRef<typeof import('vue-gtag-next')['useGtag']>
    readonly useHttpStore: UnwrapRef<typeof import('@vuetify/one')['useHttpStore']>
    readonly useI18n: UnwrapRef<typeof import('vue-i18n')['useI18n']>
    readonly useOneStore: UnwrapRef<typeof import('@vuetify/one')['useOneStore']>
    readonly usePlayground: UnwrapRef<typeof import('./src/composables/playground')['usePlayground']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useRtl: UnwrapRef<typeof import('vuetify')['useRtl']>
    readonly useTheme: UnwrapRef<typeof import('vuetify')['useTheme']>
    readonly useUserStore: UnwrapRef<typeof import('@vuetify/one')['useUserStore']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
  }
}
